<a href="https://colab.research.google.com/github/hanifaalwi/bigdata/blob/main/HanifaAlwi_Tugas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Untuk mengecek versi numpy yang kamu miliki

In [1]:
import numpy
numpy.__version__

'1.19.5'

mengimport numpy

In [2]:
import numpy as np

untuk menampilkan dokumentasi built-in numpy

In [6]:
np?

Operasi python terkait variabel

In [8]:
result = 0
for i in range(100):
  result += i

Operasi python terkait list

In [11]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

untuk mendefinisikan suatu tipe

In [12]:
type(L[0])

int

Array Tipe Tetap dengan Python

In [13]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

membuat array dengan python list

In [14]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [15]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [16]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [17]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Membuat Array dari Awal

Buat array bilangan bulat 10 panjang yang diisi dengan nol

In [18]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Buat array floating-point 3x5 yang diisi dengan 1s

In [19]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Buat array 3x5 yang diisi dengan 3.14

In [20]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

Buat array yang diisi dengan urutan linier
Mulai dari 0, berakhir pada 20, selangkah dengan 2
(ini mirip dengan fungsi range () built-in)

In [22]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Buat larik lima nilai dengan jarak yang sama antara 0 dan 1

In [23]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Buat larik 3x3 yang terdistribusi secara seragam
nilai acak antara 0 dan 1

In [24]:
np.random.random((3, 3))

array([[0.16256954, 0.98143928, 0.01852227],
       [0.90217581, 0.99804557, 0.74561552],
       [0.66352896, 0.40793863, 0.41129761]])

Buat larik 3x3 dengan nilai acak terdistribusi normal
  dengan mean 0 dan deviasi standar 1

In [25]:
np.random.normal(0, 1, (3, 3))

array([[-0.0670685 , -0.57907092,  1.0310641 ],
       [ 0.19883936,  0.15339826,  0.55517355],
       [-0.87321226,  0.67271304, -0.57280295]])

Buat array 3x3 dari bilangan bulat acak dalam interval [0, 10)

In [26]:
np.random.randint(0, 10, (3, 3))

array([[6, 6, 1],
       [2, 6, 5],
       [4, 7, 8]])

membuat matriks identitas 3x3

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Buat larik tiga bilangan bulat yang tidak diinisialisasi
Nilai apapun yang terjadi sudah ada pada saat itu
lokasi memori

In [28]:
np.empty(3)

array([1., 1., 1.])

Tipe Data Standar NumPy

In [29]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [30]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

Atribut Array NumPy

In [31]:
import numpy as np
np.random.seed(0) # benih untuk reproduktifitas
x1 = np.random.randint(10, size=6) # array 1 dimensi
x2 = np.random.randint(10, size=(3, 4)) # array 2 dimensi
x3 = np.random.randint(10, size=(3, 4, 5)) # array 3 dimensi

ndim (jumlah dimensi), shape (ukuran masing-masing
dimensi), dan size (ukuran total larik):

In [32]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


atribut dtype

In [33]:
print("dtype:", x3.dtype)

dtype: int64


itemsize : yang mencantumkan ukuran (dalam byte) dari setiap elemen array,
dan nbytes, yang mencantumkan ukuran total (dalam byte) dari array

In [34]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Mengakses Elemen Tunggal

In [35]:
x1

array([5, 0, 3, 3, 7, 9])

In [36]:
x1[0]

5

In [37]:
x1[4]

7

penggunaan tanda negatif untuk mengakses dari sisi lain array

In [38]:
x1[-1]

9

In [39]:
x1[-2]

7

array multidimensi dapat mengakses item menggunakan tupel yang dipisahkan koma dari indeks:

In [40]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
x2[0, 0]

3

In [42]:
x2[2, 0]

1

In [43]:
x2[2, -1]

7

atau jika ingin menukar isi array dengan cara

In [44]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

array NumPy memiliki tipe tetap yang berarti, jika mencoba memasukkan nilai floating-point ke array integer, file
nilai akan terpotong secara diam-diam. 

In [45]:
x1[0] = 3.14159 # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

Subarray satu dimensi

In [46]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x[:5] # 5 elemen pertama

array([0, 1, 2, 3, 4])

In [48]:
x[5:] # element setelah index 5

array([5, 6, 7, 8, 9])

In [49]:
x[4:7] # subarray tengah

array([4, 5, 6])

In [50]:
x[::2] # setiap elemen lainnya

array([0, 2, 4, 6, 8])

In [51]:
x[1::2] # setiap elemen lainnya, dimulai dari index 1

array([1, 3, 5, 7, 9])

In [52]:
x[::-1] # semua element secara terbalik

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [53]:
x[5::-2] # membalikkan elemen lainnya dari index 5

array([5, 3, 1])

subarray multidimensi

In [54]:
x2[:2, :3] # 2 baris, 3 kolum

array([[12,  5,  2],
       [ 7,  6,  8]])

In [55]:
x2[:3, ::2] # semua baris, setiap kolom lainnya

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [56]:
x2[::-1, ::-1] # membalikkan semua array 2 dimensi

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

Mengakses baris dan kolom array dapat dilakukan dengan menggabungkan pengindeksan dan pemotongan,
menggunakan irisan kosong yang ditandai dengan satu titik dua (:)

In [57]:
print(x2[:, 0]) # kolom pertama dari x2

[12  7  1]


In [58]:
print(x2[0, :]) # baris pertama dari x2

[12  5  2  4]


In [59]:
print(x2[0]) # sama dengan x2[0, :]

[12  5  2  4]


Subarray sebagai tampilan tanpa salinan (irisan array)

In [60]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [61]:
x2_sub[0, 0] = 99 # sekaligus mengganti nilai
print(x2_sub)

[[99  5]
 [ 7  6]]


In [62]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Membuat salinan array

In [63]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [64]:
x2_sub_copy[0, 0] = 42 #memodifikasi array tpi tidak dengan aslinya
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [65]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Pembentukan Ulang Array

In [66]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
x = np.array([1, 2, 3])
# vektor baris via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [68]:
# vektor baris via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [69]:
# vektor kolom via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [71]:
# vektor kolom via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

Penggabungan array

Penggabungan, atau penggabungan dua larik di NumPy, dilakukan terutama
melalui rutinitas np.concatenate, np.vstack, dan np.hstack. np.concatenate
mengambil tupel atau daftar larik sebagai argumen pertamanya:

In [72]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [73]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [74]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])
# penggabungan sepanjang axis pertama
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [75]:
# penggabungan sepanjang axis 2 (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Untuk bekerja dengan array dengan dimensi campuran, akan lebih jelas menggunakan np.vstack
(tumpukan vertikal) dan fungsi np.hstack (tumpukan horizontal)

In [76]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# tumpukan array vertikal
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [77]:
# tumpukan array horizontal
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Pemisahan array
Kebalikan dari penggabungan adalah pemisahan, yang diimplementasikan oleh fungsi
np.split, np.hsplit, dan np.vsplit. 

In [78]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [79]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [81]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


menghitung timbal balik

In [82]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
    
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

mengukur waktu eksekusi loops dengan %timeit

In [83]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1 loop, best of 5: 2.3 s per loop


In [84]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [85]:
%timeit (1.0 / big_array)

1000 loops, best of 5: 1.94 ms per loop


Operasi vektor di NumPy diimplementasikan melalui ufunc, yang tujuan utamanya adalah
untuk dengan cepat menjalankan operasi berulang pada nilai dalam array NumPy. 

In [86]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [87]:
x = np.arange(9).reshape((3, 3)) # operasi ufunc tidak terbatas pada 1 dimensi
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

array aritmatika

In [88]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) 

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [89]:
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [90]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [91]:
np.add(x, 2) #untuk penambahan

array([2, 3, 4, 5])

nilai absolute

In [92]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

hasilnya akan sama jika menggunan rumus berikut

In [93]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [94]:
np.abs(x)

array([2, 1, 0, 1, 2])

juga bisa menghandle data yang kompleks

In [95]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

Fungsi trigonometri

In [96]:
theta = np.linspace(0, np.pi, 3)

In [97]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [98]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


Eksponen 

In [99]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


Logaritma

In [100]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [101]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


submodul scipy.special untuk ufunc yang lebih terspesialisasi dan tidak jelas 

In [102]:
from scipy import special

In [103]:
# Fungsi Gamma (faktor general) dan fungsi relasi
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [104]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


argumen out berfungsi untuk menulis hasil komputasi langsung ke lokasi memori tempat Anda berada
seperti mereka

In [105]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [106]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


fungsi reduce pada add ufunc akan mengembalikan jumlah semua elemen dihimpunan

In [107]:
x = np.arange(1, 6)
np.add.reduce(x)

15

sama seperti ufunc reduce pada multiply

In [108]:
np.multiply.reduce(x)

120

In [109]:
np.add.accumulate(x) # untuk mengakumulasikan

array([ 1,  3,  6, 10, 15])

In [110]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

Metode luar untuk menghitung keluaran dari semua pasangan dari dua masukan yang berbeda 

In [111]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

menjumlahkan nilai array

In [112]:
L= np.random.random(100)
sum(L)

50.461758453195614

In [113]:
np.sum(L)

50.46175845319564

cek loop dari sum biasa banding numpy sum

In [114]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 5: 167 ms per loop
1000 loops, best of 5: 365 µs per loop


fungsi max dan fungsi min

In [115]:
min(big_array), max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [116]:
np.min(big_array), np.max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

perbandingan loop min max biasa dan numpy

In [117]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 5: 101 ms per loop
1000 loops, best of 5: 422 µs per loop


agregat multidimensi

In [118]:
M = np.random.random((3, 4))
print(M)

[[0.79832448 0.44923861 0.95274259 0.03193135]
 [0.18441813 0.71417358 0.76371195 0.11957117]
 [0.37578601 0.11936151 0.37497044 0.22944653]]


In [119]:
M.sum()

5.1136763453287335

fungsi agregat dengan menambahkan argument spesifik seperti axis

In [120]:
M.min(axis=0)

array([0.18441813, 0.11936151, 0.37497044, 0.03193135])

In [121]:
M.max(axis=1)

array([0.95274259, 0.76371195, 0.37578601])

Agregat yang tersedia di NumPy bisa sangat berguna untuk meringkas sekumpulan nilai.

In [122]:
!head -4 data/president_heights.csv

head: cannot open 'data/president_heights.csv' for reading: No such file or directory


broadcasting untuk memanggil kembali array yang berukuran sama lalu di operasikan

In [125]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [126]:
a + 5

array([5, 6, 7])